### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by chyelang** [RocShi/rocshi.github.io#1]
https://blog.shipengx.com/archives/53fe514.html
第11条中应该有typo，跟原书对不上：
`return this;  // 返回调用该函数的对象`
应该改成
`return *this;  // 返回调用该函数的对象`

**Comment by RocShi** [comment]
Hello @chyelang ，

博客对应项已更正，感谢指出 😄

![11 修正](https://user-images.githubusercontent.com/26067710/149610743-ab70e1c3-55ec-4e79-92da-4efdec73a116.png)

PS：对应原书 P233
